services:
  qq-farm-bot-ui:
    build:
      context: .
      dockerfile: core/Dockerfile
    container_name: qq-farm-bot-ui
    restart: unless-stopped
    environment:
      ADMIN_PASSWORD: admin
      TZ: Asia/Shanghai
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/core/data
      # 如果需要持久化配置，可以取消下面这行的注释
      # - ./store.json:/app/core/data/store.json
